[server]
enableStaticServing = true

[theme]
primaryColor = "#38BDF8"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E222D"
textColor = "#F8FAFC"
borderColor = "#2A2F3D"
showWidgetBorder = true
baseRadius = "6px"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#14171F"
secondaryBackgroundColor = "#1E222D"
